# Generated by Django 4.0.8 on 2023-04-26 12:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_meeting_drupal_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='drupal_duplicate_author_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='organization',
            name='drupal_duplicate_author_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='person',
            name='drupal_duplicate_author_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['civicrm_id'], name='meeting_civicrm_c09b04_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['drupal_author_id'], name='meeting_drupal__cf6e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['civicrm_id'], name='organizatio_civicrm_4d8d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['drupal_author_id'], name='organizatio_drupal__81d4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['civicrm_id'], name='person_civicrm_9c9d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['drupal_author_id'], name='person_drupal__650db4_idx'),
        ),
    ]
