# Generated by Django 4.0.8 on 2023-04-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='display_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
