# Generated by Django 4.0.8 on 2023-05-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='teaser',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
