# Generated by Django 4.0.8 on 2023-05-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='teaser',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
