# Generated by Django 4.0.8 on 2023-06-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='spotlightkenya', max_length=150, unique=True),
        ),
    ]
