# Generated by Django 4.0.8 on 2023-04-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('magazine', '0002_magazineissue_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineissue',
            name='pdf_document',
            field=models.ForeignKey(blank=True, help_text='Upload a PDF document for this issue. Note that the document will be embedded in the page and controls will be added to prohibit downloading.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
