# Generated by Django 4.0.8 on 2023-04-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_magazineissue_pdf_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazineissue',
            name='pdf_document',
        ),
    ]
